### ISSUE TITLE
question about pso

### ISSUE THREAD

**Issue by zjin-lcf** [BrownBiomechanics/Autoscoper#1]
https://github.com/BrownBiomechanics/Autoscoper/blob/master/libautoscoper/src/gpu/cuda/PSO_kernel.cu  shows that the kernels are commented.  Can you please explain that ?

Thanks

**Comment by jcfr** [comment]
For reference, the kernel was originally integrated in 

https://github.com/BrownBiomechanics/Autoscoper/commit/5c960ec7af6ece561600e17ff28de909cebbda5f (` Organized the code and tried to implement a GPU version of PSO (did not work). Function has to be modified.`), 

and later excluded in 

https://github.com/BrownBiomechanics/Autoscoper/commit/16fcbd6fdf92d61c61b455e0c2ccd294ef5df0b2 (` Fixed the problem with Deleting the values from the graph. Some printing functions to debug the SetupUI, but not complete yet.`)

**Comment by zjin-lcf** [comment]
Thanks.
