### ISSUE TITLE
Orthographic Projection

### ISSUE THREAD

**Issue by NicerNewerCar** [BrownBiomechanics/Autoscoper#120]
### Orthographic Projection resources:
* [Projection Matrix](https://en.wikipedia.org/wiki/Orthographic_projection#Geometry)
* [Learn OpenGLl](https://learnopengl.com/Getting-Started/Coordinate-Systems)
* [Scratch Pixel](https://www.scratchapixel.com/lessons/3d-basic-rendering/perspective-and-orthographic-projection-matrix/orthographic-projection-matrix.html)

### Code:

The main driver for the rendering pipeline is located here in the View class of LibAutoscoper:
https://github.com/BrownBiomechanics/Autoscoper/blob/07d880f54206c8137b2fe54cb650cd3df986fd8c/libautoscoper/src/View.cpp#L373-L422

We would likely need to implement another `DRRRenderer` that performs a parallel projection rather than the ray marching that it currently does. We would also need a way to toggle between the perspective and orthographic renderers (either at compile time or through the GUI). We also may need to update some things in the [`Camera class`](https://github.com/BrownBiomechanics/Autoscoper/blob/07d880f54206c8137b2fe54cb650cd3df986fd8c/libautoscoper/src/Camera.hpp) to get things working.

Rendering of each DRR:
https://github.com/BrownBiomechanics/Autoscoper/blob/07d880f54206c8137b2fe54cb650cd3df986fd8c/libautoscoper/src/View.cpp#L230-L236

We will likely need to update the other drivers that pass information onto the renderer:

GLView:
https://github.com/BrownBiomechanics/Autoscoper/blob/07d880f54206c8137b2fe54cb650cd3df986fd8c/autoscoper/src/ui/GLView.cpp#L507-L518
https://github.com/BrownBiomechanics/Autoscoper/blob/07d880f54206c8137b2fe54cb650cd3df986fd8c/autoscoper/src/ui/GLView.cpp#L456-L465

Tracker: 
https://github.com/BrownBiomechanics/Autoscoper/blob/07d880f54206c8137b2fe54cb650cd3df986fd8c/libautoscoper/src/Tracker.cpp#L597-L616

**Comment by NicerNewerCar** [comment]
@jcfr @amymmorton Here is my initial dive into what may need to be changed to include an orthographic projection model. Let me know what you think!

**Comment by amymmorton** [comment]
Results from our meeting: EOS is not perfectly orthographic- there is lateral distortion. Are there known libraries to 
![mp13828-fig-0001-m](https://user-images.githubusercontent.com/65619862/236281136-2427bd06-1c38-4ab6-aaf9-eaa96e49ca1d.jpg)

If the "projection" matrix changes from 

fx  0  0  0 
0  fy  0  0 
0  0  0  1

to 

1  0  0  0 
0  1  0  0 
0  0  0  1 

can we either accommodate for distortion in the x direction (radial distortion of a single direction?) or is there robustness in

fx 0  0  0 
0  1  0  0 
0  0  0  1   matrix use?




https://www.mathworks.com/help/vision/ug/camera-calibration.html

Luckner C, Herbst M, Weber T, et al. High-speed slot-scanning radiography using small-angle tomosynthesis: investigation of spatial resolution. Med Phys. 2019;. DOI: [10.1007/978-3-658-29267-6_74](https://dx.doi.org/10.1007/978-3-658-29267-6_74)
Luckner C, Ritschl L, Sesselmann S, Mertelmeier T, Maier A. Parallel‐shift tomosynthesis for orthopedic applications. Medical Imaging 2018: Physics of Medical Imaging, volume 10573:2018:15

**Comment by amymmorton** [comment]
PR #236 closes this
