### ISSUE TITLE
Tutorial suggestions

### ISSUE THREAD

**Issue by vforcesar** [BrownBiomechanics/Autoscoper#127]
Hi guys,  I think the online tutorial could benefit if you guys provide a short description of the 1) filters ("sobel"/"contrast") and the 2) "saving data parameters" . Thank you!

**Comment by NicerNewerCar** [comment]
* I added a [new tutorial](https://autoscoper--117.org.readthedocs.build/en/117/tutorials/filters.html) that goes over the basics of filters
* I added a [section about saving/loading](https://autoscoper--117.org.readthedocs.build/en/117/tutorials/sample-data.html#saving-the-tracking-results) the tracking data to the `Loading and Tracking Sample Data` tutorial.
    * This section references the [Import/Export Tracking Options](https://autoscoper--117.org.readthedocs.build/en/117/user-interface.html#import-export-tracking-options) subsection of the User Interface description that goes into detail about the different options for saving/loading tracking data. 


Let me know your thoughts on these changes!
