### ISSUE TITLE
Hiding bone option

### ISSUE THREAD

**Issue by DajungYoon** [BrownBiomechanics/Autoscoper#206]
The hide bone option currently in autoscoper will hide **all** bones. Feature request: Be able to choose which bones to hide at a time.

**Comment by NicerNewerCar** [comment]
Definitely! I think this would be very useful whenever you have lots of bones in the scene, as it can get quite hard to see what is going on.

**Comment by NicerNewerCar** [comment]
A couple of notes on the implementation for when I get around to adding this.

* Going to need to modify the `VolumeDockWidget`
    * Currently, it consists of a [`QListWidget`](https://doc.qt.io/qt-6/qlistwidget.html) that we append a string to for each volume. Will need to modify it so it can display a string and a checkbox somehow
* Add enable/disable flag to each `drrRenderer` -> when disabled fill buffer with blank values (`0x00`)
https://github.com/BrownBiomechanics/Autoscoper/blob/16e4606c95095f88d356678d9797320b9d969fea/libautoscoper/src/View.cpp#L226-L232
