### ISSUE TITLE
Update Radiograph cam subfolder to associate with trialName

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/Autoscoper#207]
As I organise our operators- I want to make sure they all create a copy of their data into the folder structure .. but I think we need to add clarity to [CFG file format/folder format](https://autoscoper.readthedocs.io/en/latest/file-specifications/config.html)

Both v1.1 and v1.0 

Version 1.1

mayaCam_csv Calibration/cam01.csv
mayaCam_csv Calibration/cam02.csv

CameraRootDir RadiographImages/cam01/
CameraRootDir RadiographImages/cam02/

VolumeFile VolumeImages/radius.tif
VolumeFlip 0 0 0
VoxelSize 0.1 0.1 0.1

RenderingResolution 512 512

OptimizationOffsets 0.1 0.1 0.1 0.1 0.1 0.1
The cam01/2 subdir should also have  task(or trial)name_cam01 that way full projects with multiple motion trials can succinctly be stored and referenced. All other elements are common to the trial and so it would be efficient to organize this way

Version 1.1

mayaCam_csv Calibration/cam01.csv
mayaCam_csv Calibration/cam02.csv

CameraRootDir RadiographImages/**thisPoseName_**cam01/
CameraRootDir RadiographImages/**thisPoseName_**cam02/

VolumeFile VolumeImages/radius.tif
VolumeFlip 0 0 0
VoxelSize 0.1 0.1 0.1

RenderingResolution 512 512

OptimizationOffsets 0.1 0.1 0.1 0.1 0.1 0.1

**Comment by amymmorton** [comment]
Also  should correct 
RenderingResolution 

to 

RenderResolution

**Comment by NicerNewerCar** [comment]
Nice catch
