### ISSUE TITLE
PSO:: getRandom returns values above/below bounds?

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/Autoscoper#217]
current code:

`float getRandom(float low, float high)
{
  return low + (high - low + 1.0f)*(float)rand() / (RAND_MAX + 1.0f);
}`

This allows positions to be populated with values above and below the max/min:
![exceedBoundsRand](https://github.com/BrownBiomechanics/Autoscoper/assets/65619862/ef4a4f40-652c-46dd-ab7f-f9924cf45dbb)

**Comment by NicerNewerCar** [comment]
Yes, it would seem that `getRandom` does return values above the upper limit.

Assuming high/low are +/- 3 and `RAND_MAX` is 100. If we get the max value returned by the rand func we can get a value greater than our max limit
```latex
low + (high - low + 1) * {rand_value} / (RAND_MAX + 1)

-3 + (3 - -3 +1) * 100 / 101

-3 + 7 * 100 / 101

-3 + 700/101

-3 + 6.930...

3.9...
```

This does not seem like the correct thing to be doing here... Luckily we can easily correct this by removing the `+1`s.
Considering that this is used to initialize the PSO, I think we should update it.
https://github.com/BrownBiomechanics/Autoscoper/blob/7accc202f67d721a578047359495a95274dfc495/libautoscoper/src/Tracker.cpp#L429-L456
Opening a PR for this now
