### ISSUE TITLE
setBackground - mayo shoulder data crash

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/Autoscoper#244]
Tested from #76

The mayo radiograph test set (shldimg0005  Prop_Int)  I have are incredibly 'dense' black when rendered. I wanted to see if setBackground could provide a better input to the ncc  calc

on setBackground (following threshold popup) a QWindowsWindow error is returned in cmd and and unhandled exception thrown line 186 Video.cpp

 
![setBackground_QWindow](https://github.com/BrownBiomechanics/Autoscoper/assets/65619862/c85a501f-5a9c-4346-b1ec-b5cdae0864fb)
![shoulder_drr_radDARK](https://github.com/BrownBiomechanics/Autoscoper/assets/65619862/50090df1-452f-4c4f-b16b-623bc2c94eb5)

With the Knee data (311135_L_Hop) the same QWindowWindows error message is populated in cmd but the unhandled exception does not occur
![setBackground_KNEEQWindow](https://github.com/BrownBiomechanics/Autoscoper/assets/65619862/f5e9e851-2c1a-403d-93cb-8c0ccb4a65ac)

**Comment by NicerNewerCar** [comment]
@amymmorton 
I was able to get a different error, by loading the same data from #203. I am getting errors within both the CUDA and OpenCL backends, the same values I tested work on the sample data.

I have not been able to reproduce the error within the Video.cpp yet. Could you send me this dataset?

The `QWindowsWindow` error is something that has been happening for a while during the start-up of the UI and will be addressed when the larger UI improvement starts.

**Comment by amymmorton** [comment]
I create a[ truncated dataset](https://drive.google.com/file/d/1yFdvPL9bcWr-SCip_NAqV2dfhcKPJDa-/view?usp=sharing) for debugging (8 frames)

**Comment by amymmorton** [comment]
And agreed- I had the error on both cuda/opencl backend builds
