### ISSUE TITLE
DRR's Visability on SAM CUDA

### ISSUE THREAD

**Issue by DajungYoon** [BrownBiomechanics/Autoscoper#246]
Through some testing with all 2.7, SAM Cuda, and SAM OpenCL, the DRR is not visible on SAM CUDA, even if the X-Ray Intensity value within the DRR Render settings are lowered. 

After messing around with the DRR Renderer settings, by changing the X-ray Intensity value, the DRR became visible. But once I saved those filter settings, and loaded the recently saved filter settings back, the DRR's were again, not visible. And if we lowered the same X-ray intensity value again, it did not seem to make any visible changes. 

.cfg file loaded in 2.7, with the same .vie settings:
![2 7_CUDA](https://github.com/BrownBiomechanics/Autoscoper/assets/93012111/fb3f7467-46e2-478c-8226-49b098a4b54e)

same .cfg file loaded in SAM Open CL, with the same .vie settings:
![SAM_OpenCL](https://github.com/BrownBiomechanics/Autoscoper/assets/93012111/6956c379-9b5b-403a-92db-7c7acbd2bd47)

same .cfg file loaded in with SAM CUDA, with the same .vie settings:
![SAM_CUDA](https://github.com/BrownBiomechanics/Autoscoper/assets/93012111/2c8112ad-9feb-4af6-8e7a-3efce9a6305b)

**Comment by amymmorton** [comment]
@DajungYoon there is a check box next to each volume that controls visibility

**Comment by DajungYoon** [comment]
Note: The DRR's are showing! The checkbox is already checked when it is loaded in. For the DRR to show, I had to uncheck and check it again. 

However, when loading the same .cfg file and .tra files on another computer, they show up as they should normally.

**Comment by NicerNewerCar** [comment]
@DajungYoon Just confirming if this issue has been resolved via 248

**Comment by DajungYoon** [comment]
@NicerNewerCar Yes, this issue has been resolved!
