### ISSUE TITLE
DRR visibility - major issues in batch (socket) processing

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/Autoscoper#247]
Unfortunately, the DRR checkbox function is a problem.
Even though the check box is selected - the drr is not 'enabled' at cfg launch (still appears hidden in image views). This means that the optimization merely copies the pose to each frame without tracking. 

Can we:
- [x]  make all volumes check *and* enabled by default?
 and/or
- [x]  allow socket-based enable functionality?
- [x]  remove the null buffer fill in RayCaster if not visible

//if (!visible_) {
    //    cudaMemset(buffer, 0, width * height * sizeof(float));
    //    return;
    //}

**Comment by NicerNewerCar** [comment]
> make all volumes check and enabled by default?
and/or

The volumes _should_ be enabled by default

> allow socket-based enable functionality?

Yup! This is a great idea.

> remove the null buffer fill in RayCaster if not visible

Not going to do this because if a volume is disabled then it will stay on the screen in the last position it was enabled.
