### ISSUE TITLE
Delete Hotkey Functionality not working in SAM GUI

### ISSUE THREAD

**Issue by DajungYoon** [BrownBiomechanics/Autoscoper#250]
Delete hotkey when opened in SAM GUI, to delete a pose on a frame is not working. 

Tested on multiple computers and keyboards, ruling out physical keyboard issues.
Tested on both CUDA and OpenCL options in the GUI, encountering the same issue.

Current Workaround:
Utilizing the advanced setting from the menu and manually inputting frame deletion details.

**Comment by NicerNewerCar** [comment]
After playing around with this, it seems that to delete a frame it must be the current frame set on the timeline slider. 

Copying and Cutting seem to work on any frame.

Pasting will only place a single frame of data on the current frame.

Attempting to copy and paste more than one frame will crash the program.

**Comment by NicerNewerCar** [comment]
Reached out to @BardiyaAk to see if there was a specific reason this was disabled.

https://github.com/BrownBiomechanics/Autoscoper/blob/644473784dd0018f5bf8518c5e5322092e4da07d/autoscoper/src/ui/AutoscoperMainWindow.cpp#L1805-L1863

In the meantime, I am working on a fix for the paste crash.
