### ISSUE TITLE
partial volume slice load error

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/Autoscoper#264]
mentioned by @DajungYoon
 
Occurring in some commit between (5.70 2023-12-16) and ( current (5.70 2024-02-28) Introduction of a bug in parsing the partial volumes.

Seen in sample ankle data:
![image](https://github.com/BrownBiomechanics/Autoscoper/assets/65619862/91283c59-3e95-41da-a3c9-dc60769d6ad9)

In the image, the drr rendering intensity was reduced to show a 'halo' which appears to be shuffling of last slice to top order. 

Did not occur in previous 5.70 2023 12 16 pre release

**Comment by jcfr** [comment]
From @DajungYoon in https://github.com/BrownBiomechanics/Autoscoper/issues/265#issue-2161679277


> ![image](https://private-user-images.githubusercontent.com/93012111/308998942-bb845bc0-3fb3-4c85-996c-22448cb6eb63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjczOTIsIm5iZiI6MTcwOTU2NzA5MiwicGF0aCI6Ii85MzAxMjExMS8zMDg5OTg5NDItYmI4NDViYzAtM2ZiMy00Yzg1LTk5NmMtMjI0NDhjYjZlYjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE1NDQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMzFlMGFiYjA5YWNmZTk3NjY5YThkNzA4MjZkMjk3ZThmN2ZmOWVkYWY3YTBkZjQ0MmM5ZTI0MmRmODcwNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kXMb_w4pF-kItPDjfO2nihT8iAos7cjMcaV0JkH031k)
> 
> Loaded in the Training Dataset in Slicer GUI - 5.7 2024-02-25.
> 
> The extra volume is not seen if loaded in Legacy Autoscoper - same filter settings, same pose, same partial volumes.

**Comment by DajungYoon** [comment]
Working version without the PV error:
![image](https://github.com/BrownBiomechanics/Autoscoper/assets/93012111/50ea0db3-4a8d-45e4-b728-d7e4dec6d035)

**Comment by DajungYoon** [comment]
Filter settings for seeing the blown up DRR : [FilterSettings_DY.txt](https://github.com/BrownBiomechanics/Autoscoper/files/14484183/FilterSettings_DY.txt)

**Comment by jcfr** [comment]
It turns the regression was introduced in https://github.com/BrownBiomechanics/Autoscoper/commit/866a5d2f3bab52f5f354a62bd8baa7afd15f588e through the following pull request:
* https://github.com/BrownBiomechanics/Autoscoper/pull/76

--------------

| Autoscoper commit | CUDA | OpenCL |
|--|--|--|
| https://github.com/BrownBiomechanics/Autoscoper/commit/cebc017fe182f0a9e8292eaeb4a2fb173bc52af2 (`COMP: Ensure Autoscoper inner-build is built with expected CUDA compiler on Linux`) | :x: | :white_check_mark:  |
| ... | ... | ... |
| https://github.com/BrownBiomechanics/Autoscoper/commit/866a5d2f3bab52f5f354a62bd8baa7afd15f588e (`ENH: Add support for 16 and 32-bit radiograph images`) | :x: | :white_check_mark:  | 
| https://github.com/BrownBiomechanics/Autoscoper/commit/644473784dd0018f5bf8518c5e5322092e4da07d (`COMP: Ensure Autoscoper inner-build is built with expected CUDA toolkit`) | :white_check_mark: | :white_check_mark:  |
