### ISSUE TITLE
Optimization failing in new update

### ISSUE THREAD

**Issue by DajungYoon** [BrownBiomechanics/Autoscoper#269]
Software: Stable Release 5.6.1
Slicer Autoscoper Version: e1faa27 (2023-03-09)
Data: JOVE dataset -https://www.jove.com/t/63535/biplanar-videoradiography-dataset-for-model-based-pose-estimation
[SOLH001A.zip](https://github.com/BrownBiomechanics/Autoscoper/files/14563587/SOLH001A.zip)

The issue arises with the optimized tracking.

In the previous version of AS (version: 619546b, 2024-01-01), here is how the tracking appeared after all frames were optimized:
https://github.com/BrownBiomechanics/Autoscoper/assets/93012111/cbb3613b-c09d-4721-b5f8-e27a516397a4

And here's how the tracking appears in the current version (version: e1faa27, 2023-03-09) after optimizing all frames:

https://github.com/BrownBiomechanics/Autoscoper/assets/93012111/0ba78419-ca4a-4590-8421-cbe565fe5304

The same dataset and parameters were used for both videos. For both videos, the perturbed Tracking folder was loaded into Autoscoper (everything set to default except rows -> column). The filtersettingsSOL_Q.vie file was loaded, then the tracking dialog was executed with these settings:
![image](https://github.com/BrownBiomechanics/Autoscoper/assets/93012111/6373e5c9-140c-4d98-b380-1f42ec3a7a60)

**Comment by mjrainbow** [comment]
We chose 6 and 6 because we got really good results with it compared to 3 and 3. Would the quaternion spline affect this? We had great results with the December build but not with the new release.

**Comment by DajungYoon** [comment]
Here is the optimizer run with the default [-3, 3]
https://github.com/BrownBiomechanics/Autoscoper/assets/93012111/17b5ab04-905c-4455-9dac-502c18c02a2e

**Comment by NicerNewerCar** [comment]
Redownloaded JOVE and I was able to reproduce this error. Working on determining the cause now.

**Comment by NicerNewerCar** [comment]
@DajungYoon The issue seems to be caused by tracking over data. Could you test the following steps for me:

* Load filters / Tracking data
* Delete all frames except for frame 0
* Track using [-6,6]

Hopefully, this workaround works for you as well.

**Comment by DajungYoon** [comment]
@NicerNewerCar Yep that workaround works! 

Although, this will not work for our workflow/accuracy because we need to use that data and then re-optimize the pose from the imported tracking data. With our previous workflow, it was able to track over data in this version: 619546b.

**Comment by NicerNewerCar** [comment]
> @NicerNewerCar Yep that workaround works!
> 
> Although, this will not work for our workflow/accuracy because we need to use that data and then re-optimize the pose from the imported tracking data. With our previous workflow, it was able to track over data in this version: 619546b.

Awesome, I have a patch that should fix this issue (see #273) I will keep you posted when that gets added to the release version.
