### ISSUE TITLE
Sample ankle data - python console

### ISSUE THREAD

**Issue by DajungYoon** [BrownBiomechanics/Autoscoper#271]
When loading in the ANKLE sample data, this error is showing up in the python console: 
FD] Tracker::trackFrame(): Volume 2 is not in view of camera 0
[FD] Tracker::trackFrame(): Volume 2 is not in view of camera 1
![image](https://github.com/BrownBiomechanics/Autoscoper/assets/93012111/52ff23ef-72ed-41be-9d77-cd5af94da34c)

This same error does not show up with other sample data. But unsure what this affects when it comes to tracking.

**Comment by NicerNewerCar** [comment]
Not an error, just a warning stating that the volumes are not within the bounds of the radiograph images. If you move Volume 2 into the center of all of the radiographs and then press `S` the warning should not be printed.
