### ISSUE TITLE
SAM crashing during optimization 

### ISSUE THREAD

**Issue by vforcesar** [BrownBiomechanics/Autoscoper#275]
SAM has been crashing on me every time I attempt to optimize. Despite using a high-quality tracking file as an initial guess, the optimization process fails. It manages to optimize for several frames, but then crashes unexpectedly.

![Capture](https://github.com/BrownBiomechanics/Autoscoper/assets/132497790/45e404d0-186b-4745-a1fc-989597879efb)
![Capture2](https://github.com/BrownBiomechanics/Autoscoper/assets/132497790/6c374f72-7ba8-46e0-bb78-88a0f553efca)

**Comment by NicerNewerCar** [comment]
I was able to determine the main cause of the crash, I will work on a patch tomorrow morning.

**Comment by vforcesar** [comment]
Thanks!
