### ISSUE TITLE
Queen's Feature Request - Body Readout

### ISSUE THREAD

**Issue by DajungYoon** [BrownBiomechanics/Autoscoper#284]
Add a toggle to provide the option to make the body readout (multi-colour translation and rotation lines at the bottom) correspond to the pivot coordinate system instead of the global coordinate system. We believe it will be easier to relate the readout curves to the body-fixed coordinate system because they are easier to interpret anatomically.
![image](https://github.com/user-attachments/assets/02d62fa4-7f73-4f17-83bd-1c4275168ec6)

**Comment by NicerNewerCar** [comment]
I think I am a little confused by what you mean by `Pivot coordinate system`, could you elaborate further on this?
