### ISSUE TITLE
Queen's Feature Request - Finer Controls With Arrow Keys

### ISSUE THREAD

**Issue by DajungYoon** [BrownBiomechanics/Autoscoper#285]
When working with manual tracking, the ability to navigate through the image using arrow keys would be highly beneficial. This functionality currently requires manually dragging the arrows. By enabling arrow key (or any key up to your discretion) navigation, users can seamlessly move the radiograph and customize the value of each key press. This approach improves efficiency by allowing quick adjustments and precise control. Add option to set the increment of the rotation and translation for each arrow press.

**Comment by NicerNewerCar** [comment]
> users can seamlessly move the radiograph

Do you mean move the DRR?

This is a good idea, we can use the up and down arrow keys to increment the value of a given DOF. Then we can use the left and right arrow keys to cycle through which DOF is active (with some UI feature to show what the currently selected DOF is). What are your thoughts on this?

**Comment by DajungYoon** [comment]
Yes sorry! I meant move the DRR. But that is exactly like what we were picturing.
