### ISSUE TITLE
Queen's Feature Request - Pivot Alignment Features 

### ISSUE THREAD

**Issue by DajungYoon** [BrownBiomechanics/Autoscoper#286]
Add a toggle to snap the pivot to the inertial coordinate system and the center of mass of the bone. This functionality allows for locking the rotation to the bone in a meaningful way, making it easier to analyze and interpret the movements and forces acting upon the bone within its anatomical position.

**Comment by NicerNewerCar** [comment]
Currently the pivot is set to the dimensional center of the volume, just to clarify, this functionality would perform a center of mass calculation to determine a more anatomical center of the volume? And by `inertial coordinate system` I assume you mean based at the COM?

**Comment by NicerNewerCar** [comment]
Using the following formula[^1] we can compute the center of mass (COM) index:

$$COM = \frac{\Sigma_{ijk} x_{ijk} * \rho_{ijk}}{\Sigma_{ijk} \rho_{ijk} }$$

Where $x_{ijk}$ is the current index `[i,j,k]` and $\rho_{ijk}$ is the attenuation value at index i, j, k.

We can then scale the COM index to to get the world position in mm. 

| |Position | Visualization |
|  - | -- | -- |
| Rad - BN00107 | ![image](https://github.com/user-attachments/assets/9717a05f-a9ea-431c-8d1a-9713d019239f) | ![image](https://github.com/user-attachments/assets/6f0d3cbc-6492-4f99-bc4e-f1d56b4b3815) | 
| Cal - SOL001A | ![image](https://github.com/user-attachments/assets/00af6e94-085c-47d6-8789-e172ae1d1136) | ![image](https://github.com/user-attachments/assets/e0eebd96-a99b-4fcc-baec-150609a6e9c6) | 
| Tal - SOL001A | ![image](https://github.com/user-attachments/assets/1ff1f92f-015e-4dee-8dc3-1bde639a4182) | ![image](https://github.com/user-attachments/assets/ae8a154c-3909-4870-ad60-8b3b94a607ce) | 






Currently Autoscoper sets the pivot to be at the centroid of the volume, I don't see the value in adding these calculations when the centroid is already a pretty good approximation for the COM. Let me know your thoughts, we can discuss this on Monday during the dev meeting.

[^1]: :[10.1101/2022.08.08.503202](http://dx.doi.org/10.1101/2022.08.08.503202)

**Comment by jcfr** [comment]
cc: @DajungYoon

**Comment by DajungYoon** [comment]
@NicerNewerCar The calculation that Autoscoper already sets is fine the way it is! Just to clarify, we wanted to see if you could add a toggle to snap it back onto the centroid, after we have physically moved the pivot off to a different place. Sometimes, we move the pivot, either off of the camera view (to get a screenshot) or for other purposes. So either a button or some sort of UI, to place it back to the centroid.
