### ISSUE TITLE
Queen's Feature Request - Loading Filter And Tracking Files With Configuration File

### ISSUE THREAD

**Issue by DajungYoon** [BrownBiomechanics/Autoscoper#289]
When starting Autoscoper and opening a trial to continue tracking a trial, you need to load the configuration (pointer) file, load the tracking file, load camera 1 filter settings, then load camera 2 filter settings. This becomes particularly cumbersome when one needs to frequently restart Autoscoper because of issues like the floating DRR. It would be efficient to have the option to specify filenames for the tracking file and camera filter settings within the configuration file, so it can all be loaded at once.

**Comment by NicerNewerCar** [comment]
Currently when autoscoper loads a `.cfg` it will look in the `xParameters` folder for `control_settings.vie` file and will apply that to both cameras.

See #210

**Comment by DajungYoon** [comment]
Sorry must have missed that one! Thanks Anthony!

**Comment by NicerNewerCar** [comment]
No worries, as it hasn't been fully integrated yet.

As another note Autoscoper will also search for tracking files with the following pattern:
`Tracking/{Config file name}_{Volume name}.tra`
