### ISSUE TITLE
Include VTK as dependency

### ISSUE THREAD

**Issue by NicerNewerCar** [BrownBiomechanics/Autoscoper#31]
Summary from 2022-08-30 meeting with @bpaniagua 
- [x] Include VTK as an external dependency
- [ ] Begin swapping VTK functions into existing workflow and comparing results

**Comment by jcfr** [comment]
* [ ] Add `libautoscoper/src/AutoscoperConfigure.h.in` file that will be configured adding the following to `libautoscoper/CMakeLists.txt`
  ```
  configure_file(
    libautoscoper/src/AutoscoperConfigure.h.in
    ${CMAKE_CURRENT_BINARY_DIR}/AutoscoperConfigure.h
    )
  ```

  and have content like the following

  ```
  #cmakedefine Autoscoper_BUILD_WITH_CUDA
  #cmakedefine Autoscoper_BUILD_WITH_VTK
  #cmakedefine Autoscoper_INSTALL_SAMPLE_DATA
  ```

  This will allow to conditionally compile different code paths ...

**Comment by jcfr** [comment]
Consider also listing below in order of priority the functionality you plan to swap with VTK equivalent functionality.

**Comment by NicerNewerCar** [comment]
Below is a table of things that need to get swapped over to VTK, all of these will need a ground truth so we have a baseline.

| Autoscoper -> VTK | Completeted |
| ----------- | ----------- |
| Filter Objects   |  NO |
| Ray Caster  | NO |
| Rad Renderer  | NO |
| Background Renderer | NO |
| View Object | NO |
|  Camera Object | NO |
|   Tiff Image Object | NO |
