### ISSUE TITLE
OpenCL Memory Leak

### ISSUE THREAD

**Issue by NicerNewerCar** [BrownBiomechanics/Autoscoper#47]
# Specs

CPU: 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
GPU: NVIDIA RTX A2000 Laptop GPU
RAM: 32GB
OS: Windows 11 Pro 64-bit Build 22000
Branch: Main

# Problem

Memory leak when tracking with OpenCL. Happens after tracking ~330 frames and produces 1 of 2 errors each time.

Error 1:
```
OpenCL error at C:\SAM\Autoscoper\libautoscoper\src\gpu\opencl\OpenCL.cpp:854
-6 CL_OUT_OF_HOST_MEMORY
``` 

[Line 854](https://github.com/BrownBiomechanics/Autoscoper/blob/56683fd2b2f729f0020d9c02538ad5c3b50bdabb/libautoscoper/src/gpu/opencl/OpenCL.cpp#L854)

Error 2:
![Screenshot 2022-10-26 152938](https://user-images.githubusercontent.com/30351234/198120669-0e790d3e-2deb-4c1c-9b04-bf04744620af.png)

Error 3:
```
Unable to allocate space for image (3097600 bytes).
OpenCL error at C:\SAM\Autoscoper\libautoscoper\src\gpu\opencl\OpenCL.cpp:1066
  -30 CL_INVALID_VALUE
```

[Line 1066](https://github.com/BrownBiomechanics/Autoscoper/blob/56683fd2b2f729f0020d9c02538ad5c3b50bdabb/libautoscoper/src/gpu/opencl/OpenCL.cpp#L1066)

While the program is running memory usage sits at ~80% while the virtual memory (committed memory) continually climbs higher until it reaches 128GB or 4 times the Physical memory at which point the program (and computer) crashes.

Windows sets the size of the paging file to be somewhere between 1.5x and 3x the amount of installed RAM for non-developer mode machines and between 1.5x and 4x for developer mode machines.

I was able to reproduce this error 6 times.

| | VM Usage | RAM Usage |
| ----------- | ----------- | ----------- |
| OpenCL |  ![OpenCl-mem-usage](https://user-images.githubusercontent.com/30351234/199262346-5a05f38a-d6ba-4a39-bba4-6003b7b30e9f.png) | ![OpenCl-available-mem](https://user-images.githubusercontent.com/30351234/199262382-b59ece35-396f-4fb7-89bc-fd1f5e327a50.png) |
| OpenCL w/ clReleaseKernel | ![OpenCL-Fixed-virtual-memory-usage](https://user-images.githubusercontent.com/30351234/206782315-1875cdc2-1ea4-4ba0-a90e-51ac0cbb6c90.png) | ![OpenCL-Fixed-available-memory](https://user-images.githubusercontent.com/30351234/206782394-17d22c6b-d52d-46b6-b31e-778f8379790c.png) |
| CUDA | ![CUDA-mem-usage](https://user-images.githubusercontent.com/30351234/199247635-524ff6b1-9292-44e6-83c7-e4d7b69dccd9.png) | ![CUDA-available-mem](https://user-images.githubusercontent.com/30351234/199247717-bfe8b955-dcfe-42a2-9b5f-37639d3a9f6f.png) |

# Dataset Loading

* Download the SampleData from the [shared drive](https://drive.google.com/file/d/17iF1rWSmOayqryQf57W84K_7zQvswNJG/view?usp=sharing)
* Head to the following subdirectory: `SampleData_internal\BVR\WRIST\NORMAL\WN00106\Autoscoper`
* Update the paths in `flx_ext.cfg` to your local paths
* Launch Autoscoper
* Click `Open Trial` and select the `flx_ext.cfg` file
* Click `Load Tracking` and use the provided .tra file making sure to select the `all` option on the volumes section
* Click `Tracking Dialog` and start tracking.

Change the file extension from `.txt` to `.tra`
[wrist-init.txt](https://github.com/BrownBiomechanics/Autoscoper/files/10058425/wrist-init.txt)

**Comment by jcfr** [comment]
Reading the following pages:
* https://doc.qt.io/qtcreator/creator-analyzer.html
* https://doc.qt.io/qtcreator/creator-heob.html

I learnt about [heob](https://github.com/ssbssa/heob) which seems to provide capabilities similar to `valgrind+memcheck` on Windows.

**Comment by NicerNewerCar** [comment]
@jcfr Some insight from Stephen McDowell:
He mentioned that the implementation of OpenCL that Nvidia ships with their drivers tends to be pretty terrible.

* Can you confirm that the memory leak is happening on linux with an nvidia gpu?

* Do you have access to a machine with a non-nvidia gpu? If so can you see if the leak is still present? If not I can get in contact with sysadmin.
