### ISSUE TITLE
Update GLEW Superbuild to pull from Github rather than SourceForge

### ISSUE THREAD

**Issue by NicerNewerCar** [BrownBiomechanics/Autoscoper#50]
https://github.com/nigels-com/glew/releases/tag/glew-2.2.0

download `glew-2.2.0.zip`

**Comment by jcfr** [comment]
Make sure to include checksum check as part of the SuperBuild external project.

**Comment by NicerNewerCar** [comment]
@jcfr The repo for release [2.2.0](https://github.com/nigels-com/glew/tree/glew-2.2.0) is missing many of the files needed to compile GLEW.

The github release [2.2.0](https://github.com/nigels-com/glew/releases/tag/glew-2.2.0) zip file has these files however github does not have support for checksums [Github community discussion #23512](https://github.com/orgs/community/discussions/23512)

**Comment by jcfr** [comment]
> re: checksum
I suggest to compute sha256 sum locally and use that value.

Specifying the checksum ensures that:
* partial download are always discarded
* changes in upstream archive are detected (e.g tag is updated, ...)

**Comment by NicerNewerCar** [comment]
@jcfr I updated the superbuild to use the release URL from github, the checksum ended up being the same value that sourceforge provides. I opened PR #54 with those changes
