### ISSUE TITLE
LIBTIFF Build Issue

### ISSUE THREAD

**Issue by NicerNewerCar** [BrownBiomechanics/Autoscoper#52]
# System Information:

Need to get more details from Madalyn Hague

OS: Windows 10/11
Compiler: Visual Studio 22?

# Issue

The building of the Tiff library fails with the following error:

`C1083: Cannot open include file unistd.h; No such file or directory`

This happens in the `zconf.h:452` file of the TIFF project.

Looks like the TIFF library is trying to include some UNIX headers rather than the windows ones. Not sure where the issue lies, waiting for more info from Maddy.

**Comment by jcfr** [comment]
Closing. As of 2023.03.29, autoscoper (https://github.com/BrownBiomechanics/Autoscoper/commit/60b3d6ec0a5e4b796ef97baaa7a3a9b0351280e7) builds successfully using `Visual Studio 17 2022`.

Please, re-open the issue providing additional details.

See https://slicer.cdash.org/index.php?project=SlicerPreview&date=2023-03-29&filtercount=2&showfilters=1&filtercombine=and&field1=site&compare1=63&value1=overload&field2=buildname&compare2=63&value2=Autoscoper
