### ISSUE TITLE
CMake build error libautoscoper

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/Autoscoper#64]
Most recent pull (12/16/2022) from main fails in build (AMM - Brown/ Kaito Lee- Queen's). 

```
CMake Error at libautoscoper/CMakeLists.txt:40 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "libautoscoper".  All uses of target_link_libraries with a
  target must be either all-keyword or all-plain.

  The uses of the plain signature are here:

   * C:/Program Files/CMake-3.24.3/share/cmake-3.24/Modules/FindCUDA.cmake:1996 (target_link_libraries)
```

See [CMakeOutput.log](https://github.com/BrownBiomechanics/Autoscoper/files/10248605/CMakeOutput.log)

**Comment by jcfr** [comment]
This is a regression I introduced in the last commit 2adc328822b13f1b0903d7a4482f1b8c8640c5c1.

Notes:
* Fix expected to be integrated in the next hour.
* To avoid future regressions:
  - A comment will be added to explain why the library has to be specified using a special syntax syntax
  - https://github.com/BrownBiomechanics/Autoscoper/issues/65
