### ISSUE TITLE
Create a Test Suit

### ISSUE THREAD

**Issue by NicerNewerCar** [BrownBiomechanics/Autoscoper#8]
Having a test suit would be extremely useful as we move into making changes and improvements to Autoscoper.

Having some sort of CI would be even nicer but not necessary.

**Comment by amymmorton** [comment]
What do you need for a test suit?

**Comment by NicerNewerCar** [comment]
@amymmorton 
We would want to create a serries of unit tests for all the methods in the code base.

This would consist of a set of inputs and ground truths for every method, so as we are adapting and integrating Autoscoper with Slicer we have a quick way to validate that everything is doing what it is supposed to.

I am not too familiar with C++ unit testing frame works so that is something we would have to look into.
