### ISSUE TITLE
Remove deprecated find_package(CUDA) 

### ISSUE THREAD

**Issue by NicerNewerCar** [BrownBiomechanics/Autoscoper#89]
* `find_packge(CUDA)` has been deprecated since CMake 3.10 and will be deprecated with a policy in an upcoming release of CMake
* We can either add `CUDA` to the list of languages in the top-level project 
* Or call `enable_language(CUDA)` before adding any `.cu` files.
* See [this page](https://cmake.org/cmake/help/latest/module/FindCUDA.html) for future reference.

**Comment by jcfr** [comment]
The path forward will be the following:
* update build-system to require at least CMake 3.17
* transition from `find_package(CUDA)` to `find_package(CUDAToolkit)`

**Comment by NicerNewerCar** [comment]
Update:

`find_package(CUDA)` has officially been deprecated with CMake 3.27 via policy [CMP0146](https://cmake.org/cmake/help/latest/policy/CMP0146.html)
